business_time:
  beginning_of_workday: 9:00 am
  end_of_workday: 5:00 pm
  holidays:
    - December 6th, 2012
    - Decemebr 25th, 2012
    - December 26th, 2012
  work_week:
    - mon
    - tue
    - wed
    - thu
    - fri
